version: "3"

services:
  app:
    container_name: deno-api
    build: .
    working_dir: /deno-api
    command: ash -c "deno upgrade && deno run --allow-all --watch app.ts"
    volumes:
      - ./app/:/deno-api
    ports:
      - "80:8000"
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Tokyo
    env_file: development.env
